import type { Icon } from '@phosphor-icons/react';
import {
  FlagIcon,
  StarIcon,
  BookOpenIcon,
  TrophyIcon,
  GraduationCapIcon,
  LightningIcon,
  PencilSimpleIcon,
  RocketIcon,
  MedalIcon,
  CrownIcon,
  FireIcon,
  DiamondIcon,
  HeartIcon,
  ShieldIcon,
  TargetIcon,
  EyeIcon,
  KeyIcon,
  CheckCircleIcon,
  UserIcon,
  SparkleIcon,
  SunIcon,
  MoonIcon,
  BeltIcon,
  SmileyIcon,
  GameControllerIcon,
  ChartLineUpIcon,
  CertificateIcon,
  BrainIcon,
  ThumbsUpIcon,
} from '@phosphor-icons/react';

export const ACHIEVEMENT_ICONS: Record<string, Icon> = {
  Flag: FlagIcon,
  Star: StarIcon,
  BookOpen: BookOpenIcon,
  Trophy: TrophyIcon,
  GraduationCap: GraduationCapIcon,
  Lightning: LightningIcon,
  PencilSimple: PencilSimpleIcon,
  Rocket: RocketIcon,
  Medal: MedalIcon,
  Crown: CrownIcon,
  Fire: FireIcon,
  Diamond: DiamondIcon,
  Heart: HeartIcon,
  Shield: ShieldIcon,
  Target: TargetIcon,
  Eye: EyeIcon,
  Key: KeyIcon,
  CheckCircle: CheckCircleIcon,
  User: UserIcon,
  Sparkle: SparkleIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Belt: BeltIcon,
  Smiley: SmileyIcon,
  GameController: GameControllerIcon,
  ChartLineUp: ChartLineUpIcon,
  Certificate: CertificateIcon,
  Brain: BrainIcon,
  ThumbsUp: ThumbsUpIcon,
};

export const DEFAULT_ICON: Icon = TrophyIcon;
